services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"               
    logstash:
      image: docker.elastic.co/logstash/logstash:7.10.1
      container_name: logstash
      ports:
        - "5044:5044"
      volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
beats:
    image: docker.elastic.co/beats/filebeat:7.10.1
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/config:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log
    command: filebeat -e -strict.perms=false