FROM python:3.13-alpine
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Add the worker script
COPY . .

# Start the worker
CMD ["python", "worker.py"]