services:
  DB:
    image: mysql:8.0               # Use MySQL version 8.0
    restart: always                # Always restart the container on failure
    environment:
      MYSQL_DATABASE: 'DV'         # Create a database named 'DV'
      MYSQL_USER: 'user'           # Create a non-root user
      MYSQL_PASSWORD: 'password'   # Password for non-root user
      MYSQL_ROOT_PASSWORD: 'rootpassword' # Root user password
    volumes:
      - mysql_data:/var/lib/mysql       # persist MySQL data
      - .:/app                # mount current dir to /app
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
